kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-nginx-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080  # The NodePort of your service inside the cluster
    hostPort: 30080        # The port on your macOS host
    listenAddress: "0.0.0.0"
    protocol : TCP
- role: worker
